[toolchain]
# pin to a specific version of the Rust toolchain
# so that performance more consistent consistent
# clarifies how rust influences parameters
channel = "1.80.0"
components = ["rust-analyzer", "tree"]
profile = "default"
